apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The revision to checkout (branch, tag, commit)
      default: "main"
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.url) .
        git checkout $(params.revision)
