apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-message
  namespace: argo-test
spec:
  params:
    - name: message
      type: string
      description: The message to print
  steps:
    - name: print
      image: busybox
      script: |
        echo $(params.message)
